FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    git unzip curl libpq-dev libzip-dev zip npm \
    && docker-php-ext-install pdo pdo_pgsql pgsql zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY . .

RUN composer install --no-dev --optimize-autoloader
RUN npm install && npm run build

RUN a2enmod rewrite

RUN chown -R www-data:www-data /var/www/html

COPY .render/apache.conf /etc/apache2/sites-available/000-default.conf

EXPOSE 80

CMD sh -c "php artisan migrate --force && apache2-foreground"